authapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import  RcLoginView, RcLogoutView, profile, ChangeUserInfoView, RcPasswordChangeView, RegisterDoneView
from .views import RegisterView, user_activate, DeleteUserView
from .captcha_decorators import check_recaptcha


urlpatterns = [
  path('login/', RcLoginView.as_view(), name = 'login'),
    path('register/',check_recaptcha(views.RegisterView.as_view()), name = 'register'),
    path('profile/', profile, name = 'profile'),
    path('logout/', RcLogoutView.as_view(), name = 'logout'),
    path('profile-change/', ChangeUserInfoView.as_view(), name = 'profile_change'),
    path('profile-delete/', DeleteUserView.as_view(), name = 'profile_delete'),
    path('register_activate/<str:sign>/', user_activate, name = 'register_activate'),
    path('register_done/', RegisterDoneView.as_view(), name = 'register_done'),
    path('password-change/', RcPasswordChangeView.as_view(), name = 'password_change'),


]

basketapp/urls.py
from django.urls import path

from .views import add, remove, basket, edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='read'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit'),
]

evoshop/evoshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name = 'main'),
    path('contacts/', mainapp.contacts, name = 'contacts'),
    path('catalog/', mainapp.catalog, name = 'catalog'),
    path('catalog/product/', mainapp.product, name = 'product'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contact/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

evoshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='кратко', max_length=60, blank=True)
    description = models.TextField(verbose_name='подробно', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='склад', default=0)
    is_hot = models.BooleanField(verbose_name='горячий продукт', default=False)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

evoshop/mainapp/views.py
import json, os
from django.shortcuts import render
from mainapp.models import Product
links_menu = [{'href': '/', 'name': 'Home'},{'href': '/catalog/', 'name': 'Catalog'},{'href': '/contacts/',
                                                                                      'name': 'Contacts'}]


def main(request):
    return render(request, 'mainapp/index.html', context={'title': 'Home','content': links_menu })



def catalog(request):
    content = {'title': 'Catalog', 'products': [{'name': 'Evolution with Arsen', 'link': '../static/img/product1.html',
                                                 'img': '../static/img/evolution_from_arsen.png'
                                                 },
                                                {'name': 'Evolution with Mark', 'link': '../static/img/product2.html',
                                                 'img': '../static/img/evolution_from_mark.jpg'
                                                 }],'content': links_menu
               }
    return render(request, 'mainapp/catalog.html', content)


def contacts(request):
    return render(request, 'mainapp/contacts.html', context={'title': 'contacts','content': links_menu })


def product(request):
    return render(request, 'mainapp/product.html', context={'title': 'Product', 'products':Product.objects.all,
                                                            'content': links_menu })

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory


def main(request):
    context = {'username': 'alexey'}
    return render(request, 'mainapp/main.html', context)


def products(request, pk=None):
    products = Product.objects.all()

    if pk or pk == 0:
        if pk != 0:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = products.filter(category=category)
        context = {'products': products, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/products.html', context)
    else:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {'hot_product': hot_product, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/hot_product.html', context)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}

    {% block css %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">

</head>
<body>
{% include 'mainapp/includes/inc_menu.html' %}

{% block content %}
{% endblock %}

{% block js %}
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Контакты</title>
{% endblock %}

{% block content %}
    <h1>Контакты</h1>
{% endblock %}

mainapp/templates/mainapp/hot_product.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1>
    <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
    <div>Общая стоимость корзины: {{ request.user|basket_total_cost }}</div>
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <div style="display: flex; flex-wrap: wrap;" class="category-products clearfix">
        <div style="margin: 20px" class="block">
              <div class="card" style="width: 18rem;">
                  <img src="/media/{{ hot_product.image }}" class="card-img-top" alt="hot_product">
                  <div class="card-body">
                      <h5 class="card-title">{{ hot_product.name }}</h5>
                      <p class="card-text">{{ hot_product.short_desc }}</p>
                      <h1 style="color: red;">ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ</h1>
                      <div style="color: red;">На складе осталось 2 товара. Спешите!!!!!!!</div>
                      <a href="{% url 'basket:add' hot_product.pk %}">Добавить в корзину</a>
                      <br>
                      <a href="{% url 'basket:remove' hot_product.pk %}">Удалить из корзины</a>
                  </div>
              </div>
          </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block content %}
    <h1 class="test">Главная</h1>
    {% if request.user.is_authenticated  %}
        <h2>Привет, {{ request.user.username|title }}!</h2>
        <a href="{% url "auth:logout" %}">Выйти</a>
        <br>
        <a href="{% url "auth:edit" request.user.pk %}">Редактировать профиль</a>
    {% else %}
        <h2>Привет!</h2>
        <a href="{% url "auth:login" %}">Войти</a>
        <br>
        <a href="{% url "auth:register" %}">Зарегистрироваться</a>
    {% endif %}
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1><br>
    <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
    <div>Общая стоимость корзины: {{ request.user|basket_total_cost }} руб.</div>
    <h3>Категории</h3>
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <br><br>
    <div style="display: flex; flex-wrap: wrap;" class="category-products clearfix">
        {% for product in products %}
            <div style="margin: 20px" class="block">
                  <div class="card" style="width: 18rem;">
                      <img src="/media/{{ product.image }}" class="card-img-top" alt="product">
                      <div class="card-body">
                          <h5 class="card-title">{{ product.name }}</h5>
                          <p class="card-text">{{ product.short_desc }}</p>
                          <a href="{% url 'basket:add' product.pk %}">Добавить в корзину</a>
                          <br>
                          <a href="{% url 'basket:remove' product.pk %}">Удалить из корзины</a>
                      </div>
                  </div>
              </div>
        {% endfor %}
    </div>
{% endblock %}